// Generated by mulciber-shader from mulciber::pbr. Do not edit.
// The shader and this evaluator are two outputs of that one source.

/// Host evaluation of the WGSL function `clamp_perceptual_roughness`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn clamp_perceptual_roughness(perceptual_roughness: f32) -> f32 {
    let __e3 = (perceptual_roughness).max(0.089f32).min(1.0f32);
    return __e3;
}

/// Host evaluation of the WGSL function `alpha_from_perceptual_roughness`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn alpha_from_perceptual_roughness(perceptual_roughness: f32) -> f32 {
    let __e1 = clamp_perceptual_roughness(perceptual_roughness);
    let __e2 = (__e1 * __e1);
    return __e2;
}

/// Host evaluation of the WGSL function `clamped_n_dot_v`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn clamped_n_dot_v(n: [f32; 3], v: [f32; 3]) -> f32 {
    let __e2 = __mulciber_dot3(n, v);
    let __e4 = (__e2).max(0.0001f32);
    return __e4;
}

/// Host evaluation of the WGSL function `f0_from_metallic`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn f0_from_metallic(base_color: [f32; 3], metallic: f32) -> [f32; 3] {
    let __e3 = [0.04f32; 3];
    let __e4 = [(__e3[0] * (1.0f32 - metallic) + base_color[0] * metallic), (__e3[1] * (1.0f32 - metallic) + base_color[1] * metallic), (__e3[2] * (1.0f32 - metallic) + base_color[2] * metallic)];
    return __e4;
}

/// Host evaluation of the WGSL function `diffuse_color_from_metallic`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn diffuse_color_from_metallic(base_color: [f32; 3], metallic: f32) -> [f32; 3] {
    let __e3 = (1.0f32 - metallic);
    let __e4 = [(base_color[0] * __e3), (base_color[1] * __e3), (base_color[2] * __e3)];
    return __e4;
}

/// Host evaluation of the WGSL function `d_ggx`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn d_ggx(n_dot_h: f32, alpha: f32) -> f32 {
    let __e1 = (alpha * alpha);
    let __e3 = (n_dot_h * __e1);
    let __e4 = (__e3 - n_dot_h);
    let __e5 = (__e4 * n_dot_h);
    let __e7 = (__e5 + 1.0f32);
    let __e9 = (3.1415927f32 * __e7);
    let __e10 = (__e9 * __e7);
    let __e11 = (__e1 / __e10);
    return __e11;
}

/// Host evaluation of the WGSL function `v_smith_ggx_correlated`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn v_smith_ggx_correlated(n_dot_v: f32, n_dot_l: f32, alpha: f32) -> f32 {
    let __e1 = (alpha * alpha);
    let __e4 = (__e1 * n_dot_v);
    let __e5 = (n_dot_v - __e4);
    let __e6 = (__e5 * n_dot_v);
    let __e7 = (__e6 + __e1);
    let __e8 = (__e7).sqrt();
    let __e9 = (n_dot_l * __e8);
    let __e10 = (__e1 * n_dot_l);
    let __e11 = (n_dot_l - __e10);
    let __e12 = (__e11 * n_dot_l);
    let __e13 = (__e12 + __e1);
    let __e14 = (__e13).sqrt();
    let __e15 = (n_dot_v * __e14);
    let __e16 = (__e9 + __e15);
    let __e18 = (0.5f32 / __e16);
    return __e18;
}

/// Host evaluation of the WGSL function `f_schlick`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn f_schlick(f0: [f32; 3], f90: f32, v_dot_h: f32) -> [f32; 3] {
    let __e2 = (1.0f32 - v_dot_h);
    let __e3 = (__e2 * __e2);
    let __e6 = [f90; 3];
    let __e7 = [(__e6[0] - f0[0]), (__e6[1] - f0[1]), (__e6[2] - f0[2])];
    let __e8 = (__e3 * __e3);
    let __e9 = (__e8 * __e2);
    let __e10 = [(__e7[0] * __e9), (__e7[1] * __e9), (__e7[2] * __e9)];
    let __e11 = [(f0[0] + __e10[0]), (f0[1] + __e10[1]), (f0[2] + __e10[2])];
    return __e11;
}

/// Host evaluation of the WGSL function `lambert`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn lambert(diffuse_color: [f32; 3]) -> [f32; 3] {
    let __e2 = [3.1415927f32; 3];
    let __e3 = [(diffuse_color[0] / __e2[0]), (diffuse_color[1] / __e2[1]), (diffuse_color[2] / __e2[2])];
    return __e3;
}

/// Host evaluation of the WGSL function `specular_brdf`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn specular_brdf(n_dot_v: f32, n_dot_l: f32, n_dot_h: f32, l_dot_h: f32, f0: [f32; 3], alpha: f32) -> [f32; 3] {
    let __e2 = d_ggx(n_dot_h, alpha);
    let __e5 = v_smith_ggx_correlated(n_dot_v, n_dot_l, alpha);
    let __e6 = (__e2 * __e5);
    let __e10 = f_schlick(f0, 1.0f32, l_dot_h);
    let __e11 = [(__e6 * __e10[0]), (__e6 * __e10[1]), (__e6 * __e10[2])];
    return __e11;
}

/// Host evaluation of the WGSL function `punctual_diffuse`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn punctual_diffuse(n: [f32; 3], l: [f32; 3], illuminance: [f32; 3], base_color: [f32; 3], metallic: f32) -> [f32; 3] {
    let __e2 = __mulciber_dot3(n, l);
    let __e3 = (__e2).max(0.0f32).min(1.0f32);
    let __e6 = diffuse_color_from_metallic(base_color, metallic);
    let __e7 = lambert(__e6);
    let __e9 = [(__e7[0] * illuminance[0]), (__e7[1] * illuminance[1]), (__e7[2] * illuminance[2])];
    let __e10 = [(__e9[0] * __e3), (__e9[1] * __e3), (__e9[2] * __e3)];
    return __e10;
}

/// Host evaluation of the WGSL function `punctual_specular`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn punctual_specular(n: [f32; 3], v: [f32; 3], l: [f32; 3], illuminance: [f32; 3], base_color: [f32; 3], metallic: f32, perceptual_roughness: f32) -> [f32; 3] {
    let __e2 = __mulciber_dot3(n, l);
    let __e3 = (__e2).max(0.0f32).min(1.0f32);
    let __e5 = (__e3 <= 0.0f32);
    if __e5 {
        let __e7 = [0.0f32; 3];
        return __e7;
    }
    let __e9 = [(v[0] + l[0]), (v[1] + l[1]), (v[2] + l[2])];
    let __e10 = __mulciber_normalize3(__e9);
    let __e11 = clamped_n_dot_v(n, v);
    let __e12 = __mulciber_dot3(n, __e10);
    let __e13 = (__e12).max(0.0f32).min(1.0f32);
    let __e14 = __mulciber_dot3(l, __e10);
    let __e15 = (__e14).max(0.0f32).min(1.0f32);
    let __e18 = f0_from_metallic(base_color, metallic);
    let __e20 = alpha_from_perceptual_roughness(perceptual_roughness);
    let __e21 = specular_brdf(__e11, __e3, __e13, __e15, __e18, __e20);
    let __e23 = [(__e21[0] * illuminance[0]), (__e21[1] * illuminance[1]), (__e21[2] * illuminance[2])];
    let __e24 = [(__e23[0] * __e3), (__e23[1] * __e3), (__e23[2] * __e3)];
    return __e24;
}

/// Host evaluation of the WGSL function `specular_dfg`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn specular_dfg(f0: [f32; 3], dfg: [f32; 2]) -> [f32; 3] {
    let __e2 = dfg[0];
    let __e3 = [__e2; 3];
    let __e4 = dfg[1];
    let __e5 = [__e4; 3];
    let __e6 = [(__e3[0] * (1.0f32 - f0[0]) + __e5[0] * f0[0]), (__e3[1] * (1.0f32 - f0[1]) + __e5[1] * f0[1]), (__e3[2] * (1.0f32 - f0[2]) + __e5[2] * f0[2])];
    return __e6;
}

/// Host evaluation of the WGSL function `energy_compensation`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn energy_compensation(f0: [f32; 3], dfg: [f32; 2]) -> [f32; 3] {
    let __e1 = dfg[1];
    let __e3 = (1.0f32 / __e1);
    let __e6 = (__e3 - 1.0f32);
    let __e7 = [(f0[0] * __e6), (f0[1] * __e6), (f0[2] * __e6)];
    let __e9 = [1.0f32; 3];
    let __e10 = [(__e9[0] + __e7[0]), (__e9[1] + __e7[1]), (__e9[2] + __e7[2])];
    return __e10;
}

/// Host evaluation of the WGSL function `environment_specular`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn environment_specular(prefiltered: [f32; 3], f0: [f32; 3], dfg: [f32; 2]) -> [f32; 3] {
    let __e2 = specular_dfg(f0, dfg);
    let __e4 = [(prefiltered[0] * __e2[0]), (prefiltered[1] * __e2[1]), (prefiltered[2] * __e2[2])];
    let __e5 = energy_compensation(f0, dfg);
    let __e6 = [(__e4[0] * __e5[0]), (__e4[1] * __e5[1]), (__e4[2] * __e5[2])];
    return __e6;
}

/// Host evaluation of the WGSL function `lod_from_roughness`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn lod_from_roughness(perceptual_roughness: f32, max_lod: f32) -> f32 {
    let __e2 = (max_lod * perceptual_roughness);
    return __e2;
}

fn __mulciber_dot3(left: [f32; 3], right: [f32; 3]) -> f32 {
    left[0] * right[0] + left[1] * right[1] + left[2] * right[2]
}

fn __mulciber_length3(value: [f32; 3]) -> f32 {
    __mulciber_dot3(value, value).sqrt()
}

fn __mulciber_normalize3(value: [f32; 3]) -> [f32; 3] {
    let scale = 1.0f32 / __mulciber_length3(value);
    [value[0] * scale, value[1] * scale, value[2] * scale]
}

