// Generated by mulciber-shader from mulciber::photometry. Do not edit.
// The shader and this evaluator are two outputs of that one source.

/// Host evaluation of the WGSL function `point_light_intensity`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn point_light_intensity(lumens: f32) -> f32 {
    let __e2 = (lumens / 12.566371f32);
    return __e2;
}

/// Host evaluation of the WGSL function `spot_light_intensity`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn spot_light_intensity(lumens: f32) -> f32 {
    let __e2 = (lumens / 3.1415927f32);
    return __e2;
}

/// Host evaluation of the WGSL function `focused_spot_light_intensity`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn focused_spot_light_intensity(lumens: f32, cos_outer: f32) -> f32 {
    let __e4 = (1.0f32 - cos_outer);
    let __e5 = (6.2831855f32 * __e4);
    let __e6 = (lumens / __e5);
    return __e6;
}

/// Host evaluation of the WGSL function `range_window`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn range_window(distance_squared: f32, range: f32) -> f32 {
    let __e2 = (range * range);
    let __e3 = (distance_squared / __e2);
    let __e4 = (__e3 * __e3);
    let __e6 = (1.0f32 - __e4);
    let __e7 = (__e6).max(0.0f32).min(1.0f32);
    let __e8 = (__e7 * __e7);
    return __e8;
}

/// Host evaluation of the WGSL function `distance_attenuation`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn distance_attenuation(distance_squared: f32, range: f32) -> f32 {
    let __e2 = range_window(distance_squared, range);
    let __e4 = (distance_squared).max(0.0001f32);
    let __e5 = (__e2 / __e4);
    return __e5;
}

/// Host evaluation of the WGSL function `punctual_illuminance`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn punctual_illuminance(intensity: f32, distance_squared: f32, range: f32) -> f32 {
    let __e2 = distance_attenuation(distance_squared, range);
    let __e4 = (intensity * __e2);
    return __e4;
}

/// Host evaluation of the WGSL function `spot_angle_attenuation`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn spot_angle_attenuation(cos_angle: f32, cos_inner: f32, cos_outer: f32) -> f32 {
    let __e2 = (cos_inner - cos_outer);
    let __e4 = (__e2).max(0.0009765625f32);
    let __e6 = (1.0f32 / __e4);
    let __e8 = (cos_angle - cos_outer);
    let __e9 = (__e8 * __e6);
    let __e10 = (__e9).max(0.0f32).min(1.0f32);
    let __e11 = (__e10 * __e10);
    return __e11;
}

/// Host evaluation of the WGSL function `ev100_from_camera`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn ev100_from_camera(aperture: f32, shutter_seconds: f32, iso: f32) -> f32 {
    let __e2 = (aperture * aperture);
    let __e3 = (__e2 / shutter_seconds);
    let __e6 = (__e3 * 100.0f32);
    let __e7 = (__e6 / iso);
    let __e8 = (__e7).log2();
    return __e8;
}

/// Host evaluation of the WGSL function `ev100_from_luminance`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn ev100_from_luminance(average_luminance: f32) -> f32 {
    let __e2 = (average_luminance * 100.0f32);
    let __e4 = (__e2 / 12.5f32);
    let __e5 = (__e4).log2();
    return __e5;
}

/// Host evaluation of the WGSL function `exposure_from_ev100`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn exposure_from_ev100(ev100: f32) -> f32 {
    let __e1 = (ev100).exp2();
    let __e3 = (1.2f32 * __e1);
    let __e5 = (1.0f32 / __e3);
    return __e5;
}

/// Host evaluation of the WGSL function `pre_expose`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn pre_expose(value: [f32; 3], exposure: f32) -> [f32; 3] {
    let __e2 = [(value[0] * exposure), (value[1] * exposure), (value[2] * exposure)];
    return __e2;
}

/// Host evaluation of the WGSL function `pre_expose_intensity`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn pre_expose_intensity(intensity: f32, exposure: f32) -> f32 {
    let __e2 = (intensity * exposure);
    return __e2;
}

