// Generated by mulciber-shader from mulciber::tonemap. Do not edit.
// The shader and this evaluator are two outputs of that one source.

/// Host evaluation of the WGSL function `hue_preserving_shoulder`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn hue_preserving_shoulder(radiance: [f32; 3]) -> [f32; 3] {
    let __e2 = [0.0f32; 3];
    let __e3 = [(radiance[0]).max(__e2[0]), (radiance[1]).max(__e2[1]), (radiance[2]).max(__e2[2])];
    let __e4 = __e3[0];
    let __e5 = __e3[1];
    let __e6 = __e3[2];
    let __e7 = (__e5).max(__e6);
    let __e8 = (__e4).max(__e7);
    let __e10 = (__e8 <= 0.6f32);
    if __e10 {
        return __e3;
    }
    let __e13 = (__e8 - 0.6f32);
    let __e14 = (0.39999998f32 * __e13);
    let __e17 = (__e8 - 0.6f32);
    let __e18 = (__e17 + 0.39999998f32);
    let __e19 = (__e14 / __e18);
    let __e20 = (0.6f32 + __e19);
    let __e21 = (__e20 / __e8);
    let __e22 = [(__e3[0] * __e21), (__e3[1] * __e21), (__e3[2] * __e21)];
    return __e22;
}

