use std::env;
use std::path::PathBuf;

fn main() {
    let mut arguments = env::args_os().skip(1);
    let headers = PathBuf::from(arguments.next().expect("expected Vulkan header directory"));
    let output = PathBuf::from(arguments.next().expect("expected output Rust file"));
    assert!(arguments.next().is_none(), "unexpected extra argument");

    let include = format!("-I{}", headers.display());
    let include_root = format!(
        "-I{}",
        headers
            .parent()
            .expect("Vulkan headers directory should have a parent")
            .display()
    );
    let wrapper = r#"
#define VK_NO_PROTOTYPES 1
#define VK_USE_PLATFORM_WIN32_KHR 1
#include "vulkan_core.h"

typedef void* HANDLE;
typedef void* HINSTANCE;
typedef void* HWND;
typedef void* HMONITOR;
typedef const unsigned short* LPCWSTR;
typedef unsigned long DWORD;
typedef struct SECURITY_ATTRIBUTES SECURITY_ATTRIBUTES;

#include "vulkan_win32.h"
"#;

    let mut builder = bindgen::Builder::default()
        .header_contents("mulciber_vulkan_wrapper.h", wrapper)
        .clang_arg(include)
        .clang_arg(include_root)
        .clang_arg("--target=x86_64-pc-windows-msvc")
        .allowlist_recursively(true)
        .derive_debug(true)
        .derive_default(true)
        .generate_comments(false)
        .layout_tests(false)
        .merge_extern_blocks(true)
        .prepend_enum_name(false)
        .use_core()
        .raw_line(
            "#![allow(\n    dead_code,\n    non_camel_case_types,\n    non_snake_case,\n    non_upper_case_globals,\n    unused_imports,\n    clippy::all,\n    clippy::pedantic\n)]",
        )
        .raw_line("// Generated by tools/vulkan-bindgen from Vulkan-Headers v1.4.356.");
    for symbol in include_str!("../symbols.txt").lines() {
        let exact = format!("^{symbol}$");
        builder = builder.allowlist_item(exact);
    }
    let bindings = builder
        .generate()
        .expect("could not generate Vulkan bindings");

    bindings
        .write_to_file(output)
        .expect("could not write Vulkan bindings");
}
