// Generated by mulciber-shader from mulciber::color. Do not edit.
// The shader and this evaluator are two outputs of that one source.

#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
fn mulciber_color_srgb_to_linear_channel(encoded: f32) -> f32 {
    let __e2 = (encoded <= 0.04045f32);
    if __e2 {
        let __e4 = (encoded / 12.92f32);
        return __e4;
    }
    let __e6 = (encoded + 0.055f32);
    let __e8 = (__e6 / 1.055f32);
    let __e10 = (__e8).powf(2.4f32);
    return __e10;
}

/// Host evaluation of the WGSL function `srgb_to_linear`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn srgb_to_linear(encoded: [f32; 3]) -> [f32; 3] {
    let __e1 = encoded[0];
    let __e2 = mulciber_color_srgb_to_linear_channel(__e1);
    let __e3 = encoded[1];
    let __e4 = mulciber_color_srgb_to_linear_channel(__e3);
    let __e5 = encoded[2];
    let __e6 = mulciber_color_srgb_to_linear_channel(__e5);
    let __e7 = [__e2, __e4, __e6];
    return __e7;
}

#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
fn mulciber_color_linear_to_srgb_channel(linear: f32) -> f32 {
    let __e2 = (linear <= 0.0031308f32);
    if __e2 {
        let __e4 = (linear * 12.92f32);
        return __e4;
    }
    let __e6 = (linear).powf(0.41666666f32);
    let __e8 = (1.055f32 * __e6);
    let __e10 = (__e8 - 0.055f32);
    return __e10;
}

/// Host evaluation of the WGSL function `linear_to_srgb`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn linear_to_srgb(linear: [f32; 3]) -> [f32; 3] {
    let __e1 = linear[0];
    let __e2 = mulciber_color_linear_to_srgb_channel(__e1);
    let __e3 = linear[1];
    let __e4 = mulciber_color_linear_to_srgb_channel(__e3);
    let __e5 = linear[2];
    let __e6 = mulciber_color_linear_to_srgb_channel(__e5);
    let __e7 = [__e2, __e4, __e6];
    return __e7;
}

/// Host evaluation of the WGSL function `luminance`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn luminance(linear: [f32; 3]) -> f32 {
    let __e4 = [0.2126f32, 0.7152f32, 0.0722f32];
    let __e5 = __mulciber_dot3(linear, __e4);
    return __e5;
}

fn __mulciber_dot3(left: [f32; 3], right: [f32; 3]) -> f32 {
    left[0] * right[0] + left[1] * right[1] + left[2] * right[2]
}

