//! Rust generation for host evaluation of designated WGSL functions.
//!
//! The generator walks the same validated Naga module that the Vulkan and Metal back ends
//! consume, so the host evaluator and the shader are two outputs of one source rather than two
//! hand-written copies. The accepted subset is deliberately narrow: pure scalar, vector, and
//! fixed-size array arithmetic. Anything that depends on GPU state — bindings, textures,
//! derivatives, atomics, barriers, workgroup memory — has no host meaning and is a generation
//! error rather than a silently different answer.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;

use naga::valid::{FunctionInfo, ModuleInfo};
use naga::{
    ArraySize, BinaryOperator, Block, Expression, Function, Handle, Literal, MathFunction, Module,
    RelationalFunction, Scalar, ScalarKind, Statement, TypeInner, UnaryOperator,
};

use crate::{ShaderBuildError, fail};

/// Generates one Rust source file exposing `functions` as host-callable evaluators.
pub(crate) fn generate(
    module: &Module,
    module_info: &ModuleInfo,
    source_label: &str,
    functions: &[&str],
) -> Result<String, ShaderBuildError> {
    if functions.is_empty() {
        return Err(fail("no host-field function was requested"));
    }
    let mut requested = Vec::new();
    for name in functions {
        let handle = module
            .functions
            .iter()
            .find(|(_, function)| function.name.as_deref() == Some(*name))
            .map(|(handle, _)| handle)
            .ok_or_else(|| {
                if module.entry_points.iter().any(|entry| entry.name == **name) {
                    fail(format!(
                        "{name} is a shader entry point; a host field is an ordinary WGSL function"
                    ))
                } else {
                    fail(format!("{name} is not a function in the WGSL module"))
                }
            })?;
        if !requested.contains(&handle) {
            requested.push(handle);
        }
    }

    let mut needed: BTreeSet<Handle<Function>> = BTreeSet::new();
    let mut pending = requested.clone();
    while let Some(handle) = pending.pop() {
        if !needed.insert(handle) {
            continue;
        }
        collect_calls(&module.functions[handle].body, &mut pending);
    }

    let mut writer = HostWriter {
        module,
        module_info,
        helpers: BTreeMap::new(),
        body: String::new(),
    };
    for (handle, _) in module.functions.iter() {
        if needed.contains(&handle) {
            writer.write_function(handle, requested.contains(&handle))?;
        }
    }

    let mut source = String::new();
    let _ = writeln!(
        source,
        "// Generated by mulciber-shader from {source_label}. Do not edit."
    );
    let _ = writeln!(
        source,
        "// The shader and this evaluator are two outputs of that one source."
    );
    source.push('\n');
    source.push_str(&writer.body);
    for definition in writer.helpers.values() {
        source.push_str(definition);
    }
    Ok(source)
}

fn collect_calls(block: &Block, pending: &mut Vec<Handle<Function>>) {
    for statement in block {
        match statement {
            Statement::Call { function, .. } => pending.push(*function),
            Statement::Block(inner) => collect_calls(inner, pending),
            Statement::If { accept, reject, .. } => {
                collect_calls(accept, pending);
                collect_calls(reject, pending);
            }
            Statement::Loop {
                body, continuing, ..
            } => {
                collect_calls(body, pending);
                collect_calls(continuing, pending);
            }
            Statement::Switch { cases, .. } => {
                for case in cases {
                    collect_calls(&case.body, pending);
                }
            }
            _ => {}
        }
    }
}

struct HostWriter<'a> {
    module: &'a Module,
    module_info: &'a ModuleInfo,
    helpers: BTreeMap<String, String>,
    body: String,
}

struct Context<'a> {
    function: &'a Function,
    info: &'a FunctionInfo,
    names: HashMap<Handle<Expression>, String>,
    temporary: usize,
}

impl HostWriter<'_> {
    fn write_function(
        &mut self,
        handle: Handle<Function>,
        public: bool,
    ) -> Result<(), ShaderBuildError> {
        let module = self.module;
        let function = &module.functions[handle];
        let name = function
            .name
            .as_deref()
            .ok_or_else(|| fail("a host-field function must be named"))?;
        let mut context = Context {
            function,
            info: &self.module_info[handle],
            names: HashMap::new(),
            temporary: 0,
        };

        let mut signature = String::new();
        for (index, argument) in function.arguments.iter().enumerate() {
            if argument.binding.is_some() {
                return Err(fail(format!(
                    "argument {index} of {name} carries a shader binding and has no host meaning"
                )));
            }
            if index > 0 {
                signature.push_str(", ");
            }
            let _ = write!(
                signature,
                "{}: {}",
                argument_name(function, index)?,
                self.rust_type(&module.types[argument.ty].inner)?
            );
        }
        let Some(result) = &function.result else {
            return Err(fail(format!(
                "{name} returns nothing, so it answers no host question"
            )));
        };
        if result.binding.is_some() {
            return Err(fail(format!(
                "the result of {name} carries a shader binding and has no host meaning"
            )));
        }
        let result = self.rust_type(&module.types[result.ty].inner)?;

        let mut body = String::new();
        if public {
            let _ = writeln!(
                body,
                "/// Host evaluation of the WGSL function `{name}`, generated by mulciber-shader."
            );
        }
        let _ = writeln!(
            body,
            "#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]"
        );
        let visibility = if public { "pub " } else { "" };
        let _ = writeln!(
            body,
            "{visibility}fn {}({signature}) -> {result} {{",
            identifier(name)?
        );
        for (local, variable) in function.local_variables.iter() {
            let declared = self.rust_type(&module.types[variable.ty].inner)?;
            let initial = match variable.init {
                Some(init) => self.expression(&mut context, init)?,
                None => self.zero_value(&module.types[variable.ty].inner)?,
            };
            let _ = writeln!(
                body,
                "    let mut __l{}: {declared} = {initial};",
                local.index()
            );
        }
        let mut statements = String::new();
        self.write_block(&mut context, &function.body, 1, &mut statements)?;
        body.push_str(&statements);
        body.push_str("}\n\n");
        self.body.push_str(&body);
        Ok(())
    }

    #[allow(clippy::too_many_lines)]
    fn write_block(
        &mut self,
        context: &mut Context<'_>,
        block: &Block,
        depth: usize,
        out: &mut String,
    ) -> Result<(), ShaderBuildError> {
        let module = self.module;
        let indent = "    ".repeat(depth);
        for statement in block {
            match statement {
                Statement::Emit(range) => {
                    for handle in range.clone() {
                        if self.is_pointer(context, handle) {
                            continue;
                        }
                        let value = self.expression(context, handle)?;
                        let name = format!("__e{}", handle.index());
                        let _ = writeln!(out, "{indent}let {name} = {value};");
                        context.names.insert(handle, name);
                    }
                }
                Statement::Block(inner) => {
                    let _ = writeln!(out, "{indent}{{");
                    self.write_block(context, inner, depth + 1, out)?;
                    let _ = writeln!(out, "{indent}}}");
                }
                Statement::If {
                    condition,
                    accept,
                    reject,
                } => {
                    let condition = self.expression(context, *condition)?;
                    let _ = writeln!(out, "{indent}if {condition} {{");
                    self.write_block(context, accept, depth + 1, out)?;
                    if reject.is_empty() {
                        let _ = writeln!(out, "{indent}}}");
                    } else {
                        let _ = writeln!(out, "{indent}}} else {{");
                        self.write_block(context, reject, depth + 1, out)?;
                        let _ = writeln!(out, "{indent}}}");
                    }
                }
                Statement::Loop {
                    body,
                    continuing,
                    break_if,
                } => {
                    // WGSL runs the continuing block after every iteration, including one ended by
                    // `continue`, which Rust's `continue` would skip. Running it at the top of the
                    // next iteration preserves that order.
                    let guard = context.temporary;
                    context.temporary += 1;
                    let _ = writeln!(out, "{indent}let mut __first{guard} = true;");
                    let _ = writeln!(out, "{indent}loop {{");
                    let _ = writeln!(out, "{indent}    if !__first{guard} {{");
                    self.write_block(context, continuing, depth + 2, out)?;
                    if let Some(break_if) = break_if {
                        let condition = self.expression(context, *break_if)?;
                        let _ = writeln!(out, "{indent}        if {condition} {{ break; }}");
                    }
                    let _ = writeln!(out, "{indent}    }}");
                    let _ = writeln!(out, "{indent}    __first{guard} = false;");
                    self.write_block(context, body, depth + 1, out)?;
                    let _ = writeln!(out, "{indent}}}");
                }
                Statement::Break => {
                    let _ = writeln!(out, "{indent}break;");
                }
                Statement::Continue => {
                    let _ = writeln!(out, "{indent}continue;");
                }
                Statement::Return { value } => {
                    let Some(value) = value else {
                        return Err(fail("a host field must return a value"));
                    };
                    let value = self.expression(context, *value)?;
                    let _ = writeln!(out, "{indent}return {value};");
                }
                Statement::Store { pointer, value } => {
                    let place = self.place(context, *pointer)?;
                    let value = self.expression(context, *value)?;
                    let _ = writeln!(out, "{indent}{place} = {value};");
                }
                Statement::Call {
                    function,
                    arguments,
                    result,
                } => {
                    let callee = module.functions[*function]
                        .name
                        .as_deref()
                        .ok_or_else(|| fail("a called WGSL function has no name"))?;
                    let callee = identifier(callee)?;
                    let mut written = Vec::new();
                    for argument in arguments {
                        written.push(self.expression(context, *argument)?);
                    }
                    let call = format!("{callee}({})", written.join(", "));
                    if let Some(result) = result {
                        let name = format!("__e{}", result.index());
                        let _ = writeln!(out, "{indent}let {name} = {call};");
                        context.names.insert(*result, name);
                    } else {
                        let _ = writeln!(out, "{indent}{call};");
                    }
                }
                other => {
                    return Err(fail(format!(
                        "{} has no proven host mapping",
                        statement_name(other)
                    )));
                }
            }
        }
        Ok(())
    }

    /// Writes the Rust spelling of the storage a WGSL pointer names.
    fn place(
        &mut self,
        context: &mut Context<'_>,
        handle: Handle<Expression>,
    ) -> Result<String, ShaderBuildError> {
        let expression = context.function.expressions[handle].clone();
        match expression {
            Expression::LocalVariable(local) => Ok(format!("__l{}", local.index())),
            Expression::AccessIndex { base, index } => {
                let base = self.place(context, base)?;
                Ok(format!("{base}[{index}]"))
            }
            Expression::Access { base, index } => {
                let length = self.pointee_length(context, base)?;
                let base = self.place(context, base)?;
                let index = self.expression(context, index)?;
                Ok(clamped_index(&base, &index, length))
            }
            Expression::GlobalVariable(_) => Err(fail(
                "a host field cannot read module-scope variables, which are GPU state",
            )),
            _ => Err(fail("this WGSL pointer has no proven host mapping")),
        }
    }

    fn pointee_length(
        &self,
        context: &Context<'_>,
        handle: Handle<Expression>,
    ) -> Result<u32, ShaderBuildError> {
        let inner = match self.expression_type(context, handle) {
            TypeInner::Pointer { base, .. } => &self.module.types[*base].inner,
            TypeInner::ValuePointer {
                size: Some(size), ..
            } => return Ok(*size as u32),
            _ => return Err(fail("indexed WGSL storage has no proven host mapping")),
        };
        value_length(inner)
    }

    fn is_pointer(&self, context: &Context<'_>, handle: Handle<Expression>) -> bool {
        matches!(
            self.expression_type(context, handle),
            TypeInner::Pointer { .. } | TypeInner::ValuePointer { .. }
        )
    }

    fn expression_type<'b>(
        &'b self,
        context: &'b Context<'_>,
        handle: Handle<Expression>,
    ) -> &'b TypeInner {
        context.info[handle].ty.inner_with(&self.module.types)
    }

    #[allow(clippy::too_many_lines)]
    fn expression(
        &mut self,
        context: &mut Context<'_>,
        handle: Handle<Expression>,
    ) -> Result<String, ShaderBuildError> {
        if let Some(name) = context.names.get(&handle) {
            return Ok(name.clone());
        }
        let module = self.module;
        let expression = context.function.expressions[handle].clone();
        match expression {
            Expression::Literal(literal) => literal_value(literal),
            Expression::Constant(constant) => {
                let init = module.constants[constant].init;
                self.constant_value(init)
            }
            Expression::ZeroValue(ty) => self.zero_value(&module.types[ty].inner),
            Expression::FunctionArgument(index) => argument_name(context.function, index as usize),
            Expression::Load { pointer } => self.place(context, pointer),
            Expression::AccessIndex { base, index } => {
                if self.is_pointer(context, base) {
                    return self.place(context, handle);
                }
                let base = self.expression(context, base)?;
                Ok(format!("{base}[{index}]"))
            }
            Expression::Access { base, index } => {
                if self.is_pointer(context, base) {
                    return self.place(context, handle);
                }
                let length = value_length(self.expression_type(context, base))?;
                let base = self.expression(context, base)?;
                let index = self.expression(context, index)?;
                Ok(clamped_index(&base, &index, length))
            }
            Expression::Splat { size, value } => {
                let value = self.expression(context, value)?;
                Ok(format!("[{value}; {}]", size as u32))
            }
            Expression::Swizzle {
                size,
                vector,
                pattern,
            } => {
                let vector = self.expression(context, vector)?;
                let temporary = bind(context, &vector);
                let components: Vec<String> = pattern[..size as usize]
                    .iter()
                    .map(|component| format!("{}[{}]", temporary.name, *component as usize))
                    .collect();
                Ok(temporary.wrap(&format!("[{}]", components.join(", "))))
            }
            Expression::Compose { components, .. } => {
                let mut parts = Vec::new();
                let mut prelude = String::new();
                for component in components {
                    let width = self.width(context, component);
                    let value = self.expression(context, component)?;
                    if let Some(size) = width {
                        let temporary = bind(context, &value);
                        prelude.push_str(&temporary.binding);
                        for index in 0..size as usize {
                            parts.push(format!("{}[{index}]", temporary.name));
                        }
                    } else {
                        parts.push(value);
                    }
                }
                let composed = format!("[{}]", parts.join(", "));
                if prelude.is_empty() {
                    Ok(composed)
                } else {
                    Ok(format!("{{ {prelude}{composed} }}"))
                }
            }
            Expression::Unary { op, expr } => {
                let kind = scalar_kind(self.expression_type(context, expr));
                let width = self.width(context, expr);
                let value = self.expression(context, expr)?;
                Ok(componentwise(context, &[(value, width)], move |parts| {
                    let value = &parts[0];
                    match (op, kind) {
                        (UnaryOperator::Negate, Some(ScalarKind::Sint)) => {
                            format!("({value}).wrapping_neg()")
                        }
                        (UnaryOperator::Negate, _) => format!("(-{value})"),
                        (UnaryOperator::LogicalNot | UnaryOperator::BitwiseNot, _) => {
                            format!("(!{value})")
                        }
                    }
                }))
            }
            Expression::Binary { op, left, right } => self.binary(context, op, left, right),
            Expression::Select {
                condition,
                accept,
                reject,
            } => {
                let condition_width = self.width(context, condition);
                let width = self.width(context, accept);
                let condition = self.expression(context, condition)?;
                let accept = self.expression(context, accept)?;
                let reject = self.expression(context, reject)?;
                Ok(componentwise(
                    context,
                    &[
                        (condition, condition_width),
                        (accept, width),
                        (reject, width),
                    ],
                    |parts| {
                        format!(
                            "(if {} {{ {} }} else {{ {} }})",
                            parts[0], parts[1], parts[2]
                        )
                    },
                ))
            }
            Expression::Relational { fun, argument } => self.relational(context, fun, argument),
            Expression::As {
                expr,
                kind,
                convert,
            } => self.convert(context, expr, kind, convert),
            Expression::Math {
                fun,
                arg,
                arg1,
                arg2,
                arg3,
            } => self.math(context, fun, arg, arg1, arg2, arg3),
            Expression::GlobalVariable(_) => Err(fail(
                "a host field cannot read module-scope variables, which are GPU state",
            )),
            Expression::CallResult(_) => Err(fail("a WGSL call result was used before its call")),
            other => Err(fail(format!(
                "{} has no proven host mapping",
                expression_name(&other)
            ))),
        }
    }

    fn relational(
        &mut self,
        context: &mut Context<'_>,
        fun: RelationalFunction,
        argument: Handle<Expression>,
    ) -> Result<String, ShaderBuildError> {
        let width = self.width(context, argument);
        let value = self.expression(context, argument)?;
        let temporary = bind(context, &value);
        let components: Vec<String> = match width {
            Some(size) => (0..size as usize)
                .map(|index| format!("{}[{index}]", temporary.name))
                .collect(),
            None => vec![temporary.name.clone()],
        };
        let expression = match fun {
            RelationalFunction::All => components.join(" && "),
            RelationalFunction::Any => components.join(" || "),
            RelationalFunction::IsNan => join_with(&components, ".is_nan()", " || "),
            RelationalFunction::IsInf => join_with(&components, ".is_infinite()", " || "),
        };
        Ok(temporary.wrap(&format!("({expression})")))
    }

    fn width(&self, context: &Context<'_>, handle: Handle<Expression>) -> Option<u32> {
        match self.expression_type(context, handle) {
            TypeInner::Vector { size, .. } => Some(*size as u32),
            _ => None,
        }
    }

    fn binary(
        &mut self,
        context: &mut Context<'_>,
        op: BinaryOperator,
        left: Handle<Expression>,
        right: Handle<Expression>,
    ) -> Result<String, ShaderBuildError> {
        use BinaryOperator as Op;
        let kind = scalar_kind(self.expression_type(context, left))
            .ok_or_else(|| fail("a WGSL operand has no proven host mapping"))?;
        let left_width = self.width(context, left);
        let right_width = self.width(context, right);
        let left = self.expression(context, left)?;
        let right = self.expression(context, right)?;
        let integer = matches!(kind, ScalarKind::Sint | ScalarKind::Uint);
        Ok(componentwise(
            context,
            &[(left, left_width), (right, right_width)],
            move |parts| {
                let (left, right) = (&parts[0], &parts[1]);
                match (op, integer) {
                    (Op::Add, true) => format!("({left}).wrapping_add({right})"),
                    (Op::Subtract, true) => format!("({left}).wrapping_sub({right})"),
                    (Op::Multiply, true) => format!("({left}).wrapping_mul({right})"),
                    (Op::Divide, true) => format!("({left}).wrapping_div({right})"),
                    (Op::Modulo, true) => format!("({left}).wrapping_rem({right})"),
                    (Op::Add, false) => format!("({left} + {right})"),
                    (Op::Subtract, false) => format!("({left} - {right})"),
                    (Op::Multiply, false) => format!("({left} * {right})"),
                    (Op::Divide, false) => format!("({left} / {right})"),
                    (Op::Modulo, false) => format!("({left} % {right})"),
                    (Op::Equal, _) => format!("({left} == {right})"),
                    (Op::NotEqual, _) => format!("({left} != {right})"),
                    (Op::Less, _) => format!("({left} < {right})"),
                    (Op::LessEqual, _) => format!("({left} <= {right})"),
                    (Op::Greater, _) => format!("({left} > {right})"),
                    (Op::GreaterEqual, _) => format!("({left} >= {right})"),
                    (Op::And, _) => format!("({left} & {right})"),
                    (Op::ExclusiveOr, _) => format!("({left} ^ {right})"),
                    (Op::InclusiveOr, _) => format!("({left} | {right})"),
                    (Op::LogicalAnd, _) => format!("({left} && {right})"),
                    (Op::LogicalOr, _) => format!("({left} || {right})"),
                    (Op::ShiftLeft, _) => format!("({left}).wrapping_shl({right})"),
                    (Op::ShiftRight, _) => format!("({left}).wrapping_shr({right})"),
                }
            },
        ))
    }

    fn convert(
        &mut self,
        context: &mut Context<'_>,
        expr: Handle<Expression>,
        kind: ScalarKind,
        convert: Option<u8>,
    ) -> Result<String, ShaderBuildError> {
        let source = scalar_kind(self.expression_type(context, expr))
            .ok_or_else(|| fail("a WGSL conversion operand has no proven host mapping"))?;
        let width = self.width(context, expr);
        let value = self.expression(context, expr)?;
        let target = scalar_name(kind)?;
        if kind == ScalarKind::Bool || source == ScalarKind::Bool {
            let to_bool = kind == ScalarKind::Bool;
            let zero_source = zero_literal(source);
            let zero_target = zero_literal(kind);
            let one_target = one_literal(kind);
            return Ok(componentwise(context, &[(value, width)], move |parts| {
                let value = &parts[0];
                if to_bool {
                    format!("({value} != {zero_source})")
                } else {
                    format!("(if {value} {{ {one_target} }} else {{ {zero_target} }})")
                }
            }));
        }
        match convert {
            Some(4) => Ok(componentwise(context, &[(value, width)], move |parts| {
                format!("(({}) as {target})", parts[0])
            })),
            None => Ok(componentwise(context, &[(value, width)], move |parts| {
                let value = &parts[0];
                match (source, kind) {
                    (ScalarKind::Float, ScalarKind::Uint) => format!("({value}).to_bits()"),
                    (ScalarKind::Float, ScalarKind::Sint) => {
                        format!("(({value}).to_bits() as i32)")
                    }
                    (ScalarKind::Uint, ScalarKind::Float) => format!("f32::from_bits({value})"),
                    (ScalarKind::Sint, ScalarKind::Float) => {
                        format!("f32::from_bits(({value}) as u32)")
                    }
                    _ => format!("(({value}) as {target})"),
                }
            })),
            Some(width) => Err(fail(format!(
                "a {width}-byte WGSL conversion has no proven host mapping"
            ))),
        }
    }

    #[allow(clippy::too_many_lines)]
    fn math(
        &mut self,
        context: &mut Context<'_>,
        fun: MathFunction,
        arg: Handle<Expression>,
        arg1: Option<Handle<Expression>>,
        arg2: Option<Handle<Expression>>,
        arg3: Option<Handle<Expression>>,
    ) -> Result<String, ShaderBuildError> {
        use MathFunction as Fun;
        let kind = scalar_kind(self.expression_type(context, arg))
            .ok_or_else(|| fail("a WGSL math operand has no proven host mapping"))?;
        let width = self.width(context, arg);
        let mut operands = vec![(self.expression(context, arg)?, width)];
        for extra in [arg1, arg2, arg3].into_iter().flatten() {
            let width = self.width(context, extra);
            let value = self.expression(context, extra)?;
            operands.push((value, width));
        }

        // Whole-vector functions consume their operands as arrays rather than component by
        // component, so they are written as helper calls.
        if matches!(
            fun,
            Fun::Dot | Fun::Cross | Fun::Distance | Fun::Reflect | Fun::Length | Fun::Normalize
        ) {
            return self.vector_math(fun, width, &operands);
        }

        let arity = operands.len();
        let expected = match fun {
            Fun::Saturate
            | Fun::Abs
            | Fun::Cos
            | Fun::Cosh
            | Fun::Sin
            | Fun::Sinh
            | Fun::Tan
            | Fun::Tanh
            | Fun::Acos
            | Fun::Asin
            | Fun::Atan
            | Fun::Asinh
            | Fun::Acosh
            | Fun::Atanh
            | Fun::Radians
            | Fun::Degrees
            | Fun::Ceil
            | Fun::Floor
            | Fun::Round
            | Fun::Fract
            | Fun::Trunc
            | Fun::Exp
            | Fun::Exp2
            | Fun::Log
            | Fun::Log2
            | Fun::Sign
            | Fun::Sqrt
            | Fun::InverseSqrt
            | Fun::CountTrailingZeros
            | Fun::CountLeadingZeros
            | Fun::CountOneBits
            | Fun::ReverseBits => 1,
            Fun::Min | Fun::Max | Fun::Atan2 | Fun::Pow | Fun::Step | Fun::Ldexp => 2,
            Fun::Clamp | Fun::Mix | Fun::SmoothStep | Fun::Fma => 3,
            other => {
                return Err(fail(format!("{other:?} has no proven host mapping")));
            }
        };
        if arity != expected {
            return Err(fail(format!(
                "{fun:?} was called with {arity} arguments rather than {expected}"
            )));
        }

        let sign = if matches!(fun, Fun::Sign) {
            self.sign_helper(kind)
        } else {
            String::new()
        };
        let integer_suffix = if matches!(kind, ScalarKind::Sint) {
            " as i32"
        } else {
            ""
        };
        Ok(componentwise(context, &operands, move |parts| {
            let first = &parts[0];
            match fun {
                Fun::Abs if matches!(kind, ScalarKind::Uint) => first.clone(),
                Fun::Abs if matches!(kind, ScalarKind::Sint) => format!("({first}).wrapping_abs()"),
                Fun::Abs => format!("({first}).abs()"),
                Fun::Min => format!("({first}).min({})", parts[1]),
                Fun::Max => format!("({first}).max({})", parts[1]),
                Fun::Clamp => format!("({first}).max({}).min({})", parts[1], parts[2]),
                Fun::Saturate => format!("({first}).max(0.0f32).min(1.0f32)"),
                Fun::Cos => format!("({first}).cos()"),
                Fun::Cosh => format!("({first}).cosh()"),
                Fun::Sin => format!("({first}).sin()"),
                Fun::Sinh => format!("({first}).sinh()"),
                Fun::Tan => format!("({first}).tan()"),
                Fun::Tanh => format!("({first}).tanh()"),
                Fun::Acos => format!("({first}).acos()"),
                Fun::Asin => format!("({first}).asin()"),
                Fun::Atan => format!("({first}).atan()"),
                Fun::Atan2 => format!("({first}).atan2({})", parts[1]),
                Fun::Asinh => format!("({first}).asinh()"),
                Fun::Acosh => format!("({first}).acosh()"),
                Fun::Atanh => format!("({first}).atanh()"),
                Fun::Radians => format!("({first}).to_radians()"),
                Fun::Degrees => format!("({first}).to_degrees()"),
                Fun::Ceil => format!("({first}).ceil()"),
                Fun::Floor => format!("({first}).floor()"),
                // WGSL rounds halfway cases to even; Rust's `round` rounds away from zero.
                Fun::Round => format!("({first}).round_ties_even()"),
                // WGSL's fract is x - floor(x); Rust's `fract` truncates toward zero instead.
                Fun::Fract => format!("({first} - ({first}).floor())"),
                Fun::Trunc => format!("({first}).trunc()"),
                Fun::Ldexp => format!("({first} * (2.0f32).powi({}))", parts[1]),
                Fun::Exp => format!("({first}).exp()"),
                Fun::Exp2 => format!("({first}).exp2()"),
                Fun::Log => format!("({first}).ln()"),
                Fun::Log2 => format!("({first}).log2()"),
                Fun::Pow => format!("({first}).powf({})", parts[1]),
                // WGSL's sign(0.0) is 0.0; Rust's `signum` answers 1.0.
                Fun::Sign => format!("{sign}({first})"),
                Fun::Fma => format!("({first}).mul_add({}, {})", parts[1], parts[2]),
                // Written as the GPU computes it: x * (1 - a) + y * a.
                Fun::Mix => {
                    let (second, blend) = (&parts[1], &parts[2]);
                    format!("({first} * (1.0f32 - {blend}) + {second} * {blend})")
                }
                Fun::Step => format!(
                    "(if {} >= {first} {{ 1.0f32 }} else {{ 0.0f32 }})",
                    parts[1]
                ),
                Fun::SmoothStep => format!(
                    "{{ let __s = (({} - {first}) / ({} - {first})).max(0.0f32).min(1.0f32); \
                     __s * __s * (3.0f32 - 2.0f32 * __s) }}",
                    parts[2], parts[1]
                ),
                Fun::Sqrt => format!("({first}).sqrt()"),
                Fun::InverseSqrt => format!("(1.0f32 / ({first}).sqrt())"),
                Fun::CountTrailingZeros => format!("(({first}).trailing_zeros(){integer_suffix})"),
                Fun::CountLeadingZeros => format!("(({first}).leading_zeros(){integer_suffix})"),
                Fun::CountOneBits => format!("(({first}).count_ones(){integer_suffix})"),
                Fun::ReverseBits => format!("({first}).reverse_bits()"),
                _ => String::new(),
            }
        }))
    }

    fn vector_math(
        &mut self,
        fun: MathFunction,
        width: Option<u32>,
        operands: &[(String, Option<u32>)],
    ) -> Result<String, ShaderBuildError> {
        use MathFunction as Fun;
        let Some(size) = width else {
            // WGSL allows the scalar overloads; they need no helper.
            let value = &operands[0].0;
            return match fun {
                Fun::Length => Ok(format!("({value}).abs()")),
                Fun::Distance => Ok(format!("({value} - {}).abs()", operands[1].0)),
                other => Err(fail(format!("scalar {other:?} has no proven host mapping"))),
            };
        };
        let arity = match fun {
            Fun::Length | Fun::Normalize => 1,
            _ => 2,
        };
        if operands.len() != arity {
            return Err(fail(format!(
                "{fun:?} was called with {} arguments rather than {arity}",
                operands.len()
            )));
        }
        if matches!(fun, Fun::Cross) && size != 3 {
            return Err(fail("cross needs three-component vectors"));
        }
        let name = match fun {
            Fun::Dot => self.helper_dot(size),
            Fun::Cross => self.helper_cross(),
            Fun::Distance => self.helper_distance(size),
            Fun::Length => self.helper_length(size),
            Fun::Normalize => self.helper_normalize(size),
            _ => self.helper_reflect(size),
        };
        let arguments: Vec<String> = operands.iter().map(|(value, _)| value.clone()).collect();
        Ok(format!("{name}({})", arguments.join(", ")))
    }

    fn sign_helper(&mut self, kind: ScalarKind) -> String {
        let scalar = if matches!(kind, ScalarKind::Sint) {
            "i32"
        } else {
            "f32"
        };
        let name = format!("__mulciber_sign_{scalar}");
        let zero = if scalar == "i32" { "0i32" } else { "0.0f32" };
        let one = if scalar == "i32" { "1i32" } else { "1.0f32" };
        let minus = if scalar == "i32" { "-1i32" } else { "-1.0f32" };
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(value: {scalar}) -> {scalar} {{\n    if value > {zero} {{\n        \
                 {one}\n    }} else if value < {zero} {{\n        {minus}\n    }} else {{\n        \
                 value\n    }}\n}}\n\n"
            )
        });
        name
    }

    fn helper_dot(&mut self, size: u32) -> String {
        let name = format!("__mulciber_dot{size}");
        let sum = (0..size)
            .map(|index| format!("left[{index}] * right[{index}]"))
            .collect::<Vec<_>>()
            .join(" + ");
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(left: [f32; {size}], right: [f32; {size}]) -> f32 {{\n    {sum}\n}}\n\n"
            )
        });
        name
    }

    fn helper_cross(&mut self) -> String {
        let name = "__mulciber_cross3".to_string();
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(left: [f32; 3], right: [f32; 3]) -> [f32; 3] {{\n    [\n        \
                 left[1] * right[2] - left[2] * right[1],\n        \
                 left[2] * right[0] - left[0] * right[2],\n        \
                 left[0] * right[1] - left[1] * right[0],\n    ]\n}}\n\n"
            )
        });
        name
    }

    fn helper_length(&mut self, size: u32) -> String {
        let dot = self.helper_dot(size);
        let name = format!("__mulciber_length{size}");
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(value: [f32; {size}]) -> f32 {{\n    {dot}(value, value).sqrt()\n}}\n\n"
            )
        });
        name
    }

    fn helper_distance(&mut self, size: u32) -> String {
        let length = self.helper_length(size);
        let name = format!("__mulciber_distance{size}");
        let difference = (0..size)
            .map(|index| format!("left[{index}] - right[{index}]"))
            .collect::<Vec<_>>()
            .join(", ");
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(left: [f32; {size}], right: [f32; {size}]) -> f32 {{\n    \
                 {length}([{difference}])\n}}\n\n"
            )
        });
        name
    }

    fn helper_normalize(&mut self, size: u32) -> String {
        let length = self.helper_length(size);
        let name = format!("__mulciber_normalize{size}");
        let components = (0..size)
            .map(|index| format!("value[{index}] * scale"))
            .collect::<Vec<_>>()
            .join(", ");
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(value: [f32; {size}]) -> [f32; {size}] {{\n    let scale = 1.0f32 / \
                 {length}(value);\n    [{components}]\n}}\n\n"
            )
        });
        name
    }

    fn helper_reflect(&mut self, size: u32) -> String {
        let dot = self.helper_dot(size);
        let name = format!("__mulciber_reflect{size}");
        let components = (0..size)
            .map(|index| format!("incident[{index}] - 2.0f32 * scale * normal[{index}]"))
            .collect::<Vec<_>>()
            .join(", ");
        self.helpers.entry(name.clone()).or_insert_with(|| {
            format!(
                "fn {name}(incident: [f32; {size}], normal: [f32; {size}]) -> [f32; {size}] {{\n    \
                 let scale = {dot}(normal, incident);\n    [{components}]\n}}\n\n"
            )
        });
        name
    }

    fn constant_value(&mut self, handle: Handle<Expression>) -> Result<String, ShaderBuildError> {
        let module = self.module;
        match &module.global_expressions[handle] {
            Expression::Literal(literal) => literal_value(*literal),
            Expression::ZeroValue(ty) => self.zero_value(&module.types[*ty].inner),
            Expression::Constant(constant) => {
                let init = module.constants[*constant].init;
                self.constant_value(init)
            }
            Expression::Splat { size, value } => {
                let size = *size as u32;
                let value = self.constant_value(*value)?;
                Ok(format!("[{value}; {size}]"))
            }
            Expression::Compose { components, .. } => {
                let components = components.clone();
                let mut parts = Vec::new();
                for component in components {
                    parts.push(self.constant_value(component)?);
                }
                Ok(format!("[{}]", parts.join(", ")))
            }
            _ => Err(fail(
                "this WGSL constant is not a literal value and has no proven host mapping",
            )),
        }
    }

    fn rust_type(&self, inner: &TypeInner) -> Result<String, ShaderBuildError> {
        match inner {
            TypeInner::Scalar(scalar) => scalar_type(*scalar),
            TypeInner::Vector { size, scalar } => {
                Ok(format!("[{}; {}]", scalar_type(*scalar)?, *size as u32))
            }
            TypeInner::Array {
                base,
                size: ArraySize::Constant(size),
                ..
            } => Ok(format!(
                "[{}; {}]",
                self.rust_type(&self.module.types[*base].inner)?,
                size.get()
            )),
            _ => Err(fail("this WGSL type has no proven host mapping")),
        }
    }

    fn zero_value(&self, inner: &TypeInner) -> Result<String, ShaderBuildError> {
        match inner {
            TypeInner::Scalar(scalar) => Ok(zero_literal(scalar.kind).to_string()),
            TypeInner::Vector { size, scalar } => {
                Ok(format!("[{}; {}]", zero_literal(scalar.kind), *size as u32))
            }
            TypeInner::Array {
                base,
                size: ArraySize::Constant(size),
                ..
            } => Ok(format!(
                "[{}; {}]",
                self.zero_value(&self.module.types[*base].inner)?,
                size.get()
            )),
            _ => Err(fail("this WGSL type has no proven host mapping")),
        }
    }
}

/// Binds a value to a temporary when it must be read more than once.
fn bind(context: &mut Context<'_>, value: &str) -> Temporary {
    // Names, indexed components, and literals cost nothing to repeat.
    if value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || "_.[]".contains(character))
    {
        return Temporary {
            name: value.to_string(),
            binding: String::new(),
        };
    }
    let index = context.temporary;
    context.temporary += 1;
    let name = format!("__t{index}");
    Temporary {
        binding: format!("let {name} = {value}; "),
        name,
    }
}

/// Applies `build` to matching components of scalar or vector operands, broadcasting scalars.
fn componentwise(
    context: &mut Context<'_>,
    operands: &[(String, Option<u32>)],
    build: impl Fn(&[String]) -> String,
) -> String {
    let mut prelude = String::new();
    let mut bound = Vec::new();
    for (value, width) in operands {
        let temporary = bind(context, value);
        prelude.push_str(&temporary.binding);
        bound.push((temporary.name, *width));
    }
    let Some(size) = operands.iter().filter_map(|(_, size)| *size).max() else {
        let parts: Vec<String> = bound.iter().map(|(name, _)| name.clone()).collect();
        let text = build(&parts);
        return if prelude.is_empty() {
            text
        } else {
            format!("{{ {prelude}{text} }}")
        };
    };
    let mut components = Vec::new();
    for index in 0..size as usize {
        let parts: Vec<String> = bound
            .iter()
            .map(|(name, width)| match width {
                Some(_) => format!("{name}[{index}]"),
                None => name.clone(),
            })
            .collect();
        components.push(build(&parts));
    }
    let composed = format!("[{}]", components.join(", "));
    if prelude.is_empty() {
        composed
    } else {
        format!("{{ {prelude}{composed} }}")
    }
}

struct Temporary {
    name: String,
    binding: String,
}

impl Temporary {
    fn wrap(&self, expression: &str) -> String {
        if self.binding.is_empty() {
            expression.to_string()
        } else {
            format!("{{ {}{expression} }}", self.binding)
        }
    }
}

fn join_with(components: &[String], suffix: &str, separator: &str) -> String {
    components
        .iter()
        .map(|component| format!("({component}){suffix}"))
        .collect::<Vec<_>>()
        .join(separator)
}

fn clamped_index(base: &str, index: &str, length: u32) -> String {
    // Naga's default bounds-check policy clamps out-of-range indices; Rust would panic.
    format!(
        "{base}[(({index}) as usize).min({})]",
        length.saturating_sub(1)
    )
}

fn value_length(inner: &TypeInner) -> Result<u32, ShaderBuildError> {
    match inner {
        TypeInner::Vector { size, .. } => Ok(*size as u32),
        TypeInner::Array {
            size: ArraySize::Constant(size),
            ..
        } => Ok(size.get()),
        _ => Err(fail("indexed WGSL values have no proven host mapping")),
    }
}

fn argument_name(function: &Function, index: usize) -> Result<String, ShaderBuildError> {
    let argument = function
        .arguments
        .get(index)
        .ok_or_else(|| fail("a WGSL argument reference is out of range"))?;
    match &argument.name {
        Some(name) => identifier(name),
        None => Ok(format!("argument{index}")),
    }
}

fn scalar_kind(inner: &TypeInner) -> Option<ScalarKind> {
    match inner {
        TypeInner::Scalar(scalar) | TypeInner::Vector { scalar, .. } => Some(scalar.kind),
        _ => None,
    }
}

fn scalar_type(scalar: Scalar) -> Result<String, ShaderBuildError> {
    match (scalar.kind, scalar.width) {
        (ScalarKind::Float, 4) => Ok("f32".to_string()),
        (ScalarKind::Sint, 4) => Ok("i32".to_string()),
        (ScalarKind::Uint, 4) => Ok("u32".to_string()),
        (ScalarKind::Bool, _) => Ok("bool".to_string()),
        _ => Err(fail("this WGSL scalar type has no proven host mapping")),
    }
}

fn scalar_name(kind: ScalarKind) -> Result<&'static str, ShaderBuildError> {
    match kind {
        ScalarKind::Float => Ok("f32"),
        ScalarKind::Sint => Ok("i32"),
        ScalarKind::Uint => Ok("u32"),
        ScalarKind::Bool => Ok("bool"),
        _ => Err(fail("this WGSL scalar kind has no proven host mapping")),
    }
}

fn zero_literal(kind: ScalarKind) -> &'static str {
    match kind {
        ScalarKind::Float | ScalarKind::AbstractFloat => "0.0f32",
        ScalarKind::Sint | ScalarKind::AbstractInt => "0i32",
        ScalarKind::Uint => "0u32",
        ScalarKind::Bool => "false",
    }
}

fn one_literal(kind: ScalarKind) -> &'static str {
    match kind {
        ScalarKind::Float | ScalarKind::AbstractFloat => "1.0f32",
        ScalarKind::Sint | ScalarKind::AbstractInt => "1i32",
        ScalarKind::Uint => "1u32",
        ScalarKind::Bool => "true",
    }
}

fn literal_value(literal: Literal) -> Result<String, ShaderBuildError> {
    match literal {
        Literal::F32(value) => Ok(float_literal(value)),
        Literal::I32(value) => Ok(format!("{value}i32")),
        Literal::U32(value) => Ok(format!("{value}u32")),
        Literal::AbstractInt(value) => Ok(format!("{value}i32")),
        _ => Err(fail("this WGSL literal has no proven host mapping")),
    }
}

fn float_literal(value: f32) -> String {
    if value.is_nan() {
        return "f32::NAN".to_string();
    }
    if value.is_infinite() {
        return if value > 0.0 {
            "f32::INFINITY".to_string()
        } else {
            "f32::NEG_INFINITY".to_string()
        };
    }
    let text = format!("{value:?}");
    if text.contains('.') || text.contains('e') {
        format!("{text}f32")
    } else {
        format!("{text}.0f32")
    }
}

/// Rust keywords a WGSL name can collide with. Raw identifiers cover all but four.
const KEYWORDS: &[&str] = &[
    "as", "async", "await", "become", "box", "break", "const", "continue", "crate", "do", "dyn",
    "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let",
    "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
    "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof", "unsafe",
    "unsized", "use", "virtual", "where", "while", "yield", "Self",
];

const UNUSABLE: &[&str] = &["crate", "self", "super", "Self"];

fn identifier(name: &str) -> Result<String, ShaderBuildError> {
    if UNUSABLE.contains(&name) {
        return Err(fail(format!(
            "the WGSL name {name} cannot be spelled in Rust; rename it"
        )));
    }
    if KEYWORDS.contains(&name) {
        return Ok(format!("r#{name}"));
    }
    Ok(name.to_string())
}

fn statement_name(statement: &Statement) -> &'static str {
    match statement {
        Statement::Switch { .. } => "a WGSL switch",
        Statement::Kill => "discard",
        Statement::ControlBarrier(_) | Statement::MemoryBarrier(_) => "a barrier",
        Statement::ImageStore { .. } => "an image store",
        Statement::Atomic { .. } | Statement::ImageAtomic { .. } => "an atomic operation",
        _ => "this WGSL statement",
    }
}

fn expression_name(expression: &Expression) -> &'static str {
    match expression {
        Expression::ImageSample { .. } | Expression::ImageLoad { .. } => "a texture read",
        Expression::ImageQuery { .. } => "a texture query",
        Expression::Derivative { .. } => "a derivative",
        Expression::ArrayLength(_) => "an array length",
        Expression::Override(_) => "a pipeline-overridable constant",
        _ => "this WGSL expression",
    }
}

#[cfg(test)]
mod tests {
    use naga::valid::{Capabilities, ValidationFlags, Validator};

    use super::generate;

    /// The generated host half of the Vulkan probe's field, checked in so review sees the Rust the
    /// generator emits and so a change to the generator has to be looked at rather than absorbed.
    mod generated {
        include!("host_field_fixture.rs");
    }

    const FIELD_WGSL: &str = include_str!("../../../probes/vulkan-triangle/src/field.wgsl");

    fn emit_labelled(
        source: &str,
        label: &str,
        functions: &[&str],
    ) -> Result<String, super::ShaderBuildError> {
        let module = naga::front::wgsl::parse_str(source).expect("test WGSL parses");
        let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
            .validate(&module)
            .expect("test WGSL validates");
        generate(&module, &info, label, functions)
    }

    fn emit(source: &str, functions: &[&str]) -> Result<String, super::ShaderBuildError> {
        emit_labelled(source, "test.wgsl", functions)
    }

    #[test]
    fn probe_field_generation_matches_the_checked_in_evaluator() {
        let generated = emit_labelled(
            FIELD_WGSL,
            "field.wgsl",
            &["surface_height", "sample_direction"],
        )
        .expect("the probe field generates");
        let expected = include_str!("host_field_fixture.rs");
        if generated != expected {
            let line = generated
                .lines()
                .zip(expected.lines())
                .position(|(left, right)| left != right)
                .unwrap_or(0);
            panic!(
                "regenerate crates/mulciber-shader/src/host_field_fixture.rs; line {} generates \n\
                 {:?}\nwhere the fixture has\n{:?}",
                line + 1,
                generated.lines().nth(line),
                expected.lines().nth(line)
            );
        }
    }

    /// The eight heights below were read back from the compute dispatch of the same WGSL on an
    /// Nvidia RTX 3060 Ti under Vulkan 1.4, where the probe measured the whole 256-direction set
    /// agreeing to 0.000402 m across a 348.6 m surface range.
    #[test]
    fn generated_field_answers_the_heights_the_gpu_computed() {
        let device = [
            15.981_661_f32,
            5.478_725_4,
            -45.968_113,
            20.010_891,
            71.376_18,
            -6.667_826_7,
            -56.083_607,
            64.797_92,
        ];
        for (index, expected) in device.iter().enumerate() {
            let sample = u32::try_from(index).expect("sample index fits u32");
            let height = generated::surface_height(generated::sample_direction(sample));
            assert!(
                (height - expected).abs() < 0.01,
                "sample {index}: host {height} m against device {expected} m"
            );
        }
    }

    #[test]
    fn wgsl_semantics_are_generated_as_the_shader_computes_them() {
        let source = "
            fn probe(value: f32, count: u32) -> f32 {
                let wrapped = count * 2654435769u;
                return fract(value) + sign(value) + round(value) + f32(wrapped);
            }
        ";
        let generated = emit(source, &["probe"]).expect("the probe function generates");
        // WGSL fract is x - floor(x); Rust's fract truncates toward zero.
        assert!(generated.contains(").floor())"));
        assert!(!generated.contains(".fract()"));
        // WGSL rounds halfway cases to even, and its integer arithmetic wraps.
        assert!(generated.contains(".round_ties_even()"));
        assert!(generated.contains(".wrapping_mul(2654435769u32)"));
        // WGSL sign(0.0) is 0.0, which Rust's signum does not answer.
        assert!(generated.contains("__mulciber_sign_f32"));
        assert!(!generated.contains(".signum()"));
    }

    #[test]
    fn gpu_state_is_not_host_evaluable() {
        let source = "
            @group(0) @binding(0) var<uniform> scale: f32;
            fn scaled(value: f32) -> f32 { return value * scale; }
        ";
        let failure = emit(source, &["scaled"]).expect_err("module-scope state is refused");
        assert!(failure.to_string().contains("module-scope variables"));
    }

    #[test]
    fn texture_reads_are_not_host_evaluable() {
        let source = "
            @group(0) @binding(0) var albedo: texture_2d<f32>;
            @group(0) @binding(1) var albedo_sampler: sampler;
            fn sampled(uv: vec2<f32>) -> vec4<f32> {
                return textureSampleLevel(albedo, albedo_sampler, uv, 0.0);
            }
        ";
        let failure = emit(source, &["sampled"]).expect_err("texture reads are refused");
        assert!(failure.to_string().contains("no proven host mapping"));
    }

    #[test]
    fn entry_points_are_not_host_fields() {
        let source = "
            @vertex fn main_vertex() -> @builtin(position) vec4<f32> {
                return vec4<f32>(0.0, 0.0, 0.0, 1.0);
            }
        ";
        let failure = emit(source, &["main_vertex"]).expect_err("entry points are refused");
        assert!(failure.to_string().contains("shader entry point"));
    }

    #[test]
    fn unmapped_types_are_refused() {
        let source = "
            fn rotated(transform: mat3x3<f32>, point: vec3<f32>) -> vec3<f32> {
                return transform * point;
            }
        ";
        let failure = emit(source, &["rotated"]).expect_err("matrices are refused");
        assert!(failure.to_string().contains("no proven host mapping"));
    }

    #[test]
    fn missing_functions_are_named_in_the_failure() {
        let failure = emit(FIELD_WGSL, &["terrain_height"]).expect_err("unknown names are refused");
        assert!(
            failure
                .to_string()
                .contains("terrain_height is not a function")
        );
    }
}
