// Generated by mulciber-shader from field.wgsl. Do not edit.
// The shader and this evaluator are two outputs of that one source.

#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
fn lattice_value(cell: [i32; 3]) -> f32 {
    let mut __l0: u32 = 0u32;
    let __e1 = cell[0];
    let __e2 = ((__e1) as u32);
    let __e4 = (__e2).wrapping_mul(2654435769u32);
    __l0 = __e4;
    let __e6 = __l0;
    let __e7 = cell[1];
    let __e8 = ((__e7) as u32);
    let __e10 = (__e8).wrapping_mul(2246822507u32);
    let __e11 = (__e6 ^ __e10);
    __l0 = __e11;
    let __e12 = __l0;
    let __e13 = cell[2];
    let __e14 = ((__e13) as u32);
    let __e16 = (__e14).wrapping_mul(3266489909u32);
    let __e17 = (__e12 ^ __e16);
    __l0 = __e17;
    let __e18 = __l0;
    let __e19 = __l0;
    let __e21 = (__e19).wrapping_shr(15u32);
    let __e22 = (__e18 ^ __e21);
    __l0 = __e22;
    let __e23 = __l0;
    let __e25 = (__e23).wrapping_mul(739982445u32);
    __l0 = __e25;
    let __e26 = __l0;
    let __e27 = __l0;
    let __e29 = (__e27).wrapping_shr(12u32);
    let __e30 = (__e26 ^ __e29);
    __l0 = __e30;
    let __e31 = __l0;
    let __e33 = (__e31).wrapping_mul(695872825u32);
    __l0 = __e33;
    let __e34 = __l0;
    let __e35 = __l0;
    let __e37 = (__e35).wrapping_shr(15u32);
    let __e38 = (__e34 ^ __e37);
    __l0 = __e38;
    let __e39 = __l0;
    let __e41 = (__e39 & 16777215u32);
    let __e42 = ((__e41) as f32);
    let __e44 = (__e42 / 16777215.0f32);
    return __e44;
}

#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
fn value_noise(point: [f32; 3]) -> f32 {
    let mut __l0: f32 = 0.0f32;
    let mut __l1: u32 = 0u32;
    let __e1 = [(point[0]).floor(), (point[1]).floor(), (point[2]).floor()];
    let __e2 = [((__e1[0]) as i32), ((__e1[1]) as i32), ((__e1[2]) as i32)];
    let __e3 = [(point[0] - __e1[0]), (point[1] - __e1[1]), (point[2] - __e1[2])];
    let __e4 = [(__e3[0] * __e3[0]), (__e3[1] * __e3[1]), (__e3[2] * __e3[2])];
    let __e6 = [(2.0f32 * __e3[0]), (2.0f32 * __e3[1]), (2.0f32 * __e3[2])];
    let __e8 = [3.0f32; 3];
    let __e9 = [(__e8[0] - __e6[0]), (__e8[1] - __e6[1]), (__e8[2] - __e6[2])];
    let __e10 = [(__e4[0] * __e9[0]), (__e4[1] * __e9[1]), (__e4[2] * __e9[2])];
    let mut __first0 = true;
    loop {
        if !__first0 {
            let __e50 = __l1;
            let __e52 = (__e50).wrapping_add(1u32);
            __l1 = __e52;
        }
        __first0 = false;
        let __e15 = __l1;
        let __e17 = (__e15 < 8u32);
        if __e17 {
        } else {
            break;
        }
        {
            let __e18 = __l1;
            let __e20 = (__e18 & 1u32);
            let __e21 = ((__e20) as i32);
            let __e22 = __l1;
            let __e24 = (__e22).wrapping_shr(1u32);
            let __e26 = (__e24 & 1u32);
            let __e27 = ((__e26) as i32);
            let __e28 = __l1;
            let __e30 = (__e28).wrapping_shr(2u32);
            let __e32 = (__e30 & 1u32);
            let __e33 = ((__e32) as i32);
            let __e34 = [__e21, __e27, __e33];
            let __e36 = [1.0f32; 3];
            let __e37 = [(__e36[0] - __e10[0]), (__e36[1] - __e10[1]), (__e36[2] - __e10[2])];
            let __e38 = [((__e34[0]) as f32), ((__e34[1]) as f32), ((__e34[2]) as f32)];
            let __e39 = [(__e37[0] * (1.0f32 - __e38[0]) + __e10[0] * __e38[0]), (__e37[1] * (1.0f32 - __e38[1]) + __e10[1] * __e38[1]), (__e37[2] * (1.0f32 - __e38[2]) + __e10[2] * __e38[2])];
            let __e40 = __l0;
            let __e41 = [(__e2[0]).wrapping_add(__e34[0]), (__e2[1]).wrapping_add(__e34[1]), (__e2[2]).wrapping_add(__e34[2])];
            let __e42 = lattice_value(__e41);
            let __e43 = __e39[0];
            let __e44 = (__e42 * __e43);
            let __e45 = __e39[1];
            let __e46 = (__e44 * __e45);
            let __e47 = __e39[2];
            let __e48 = (__e46 * __e47);
            let __e49 = (__e40 + __e48);
            __l0 = __e49;
        }
    }
    let __e53 = __l0;
    let __e55 = (__e53 * 2.0f32);
    let __e57 = (__e55 - 1.0f32);
    return __e57;
}

/// Host evaluation of the WGSL function `surface_height`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn surface_height(direction: [f32; 3]) -> f32 {
    let mut __l0: [f32; 3] = [0.0f32; 3];
    let mut __l1: f32 = 120.0f32;
    let mut __l2: f32 = 0.0f32;
    let mut __l3: u32 = 0u32;
    let __e1 = __mulciber_normalize3(direction);
    let __e3 = [(__e1[0] * 3.0f32), (__e1[1] * 3.0f32), (__e1[2] * 3.0f32)];
    __l0 = __e3;
    let mut __first0 = true;
    loop {
        if !__first0 {
            let __e26 = __l3;
            let __e28 = (__e26).wrapping_add(1u32);
            __l3 = __e28;
        }
        __first0 = false;
        let __e11 = __l3;
        let __e13 = (__e11 < 5u32);
        if __e13 {
        } else {
            break;
        }
        {
            let __e14 = __l2;
            let __e15 = __l0;
            let __e16 = value_noise(__e15);
            let __e17 = __l1;
            let __e18 = (__e16 * __e17);
            let __e19 = (__e14 + __e18);
            __l2 = __e19;
            let __e20 = __l0;
            let __e22 = [(__e20[0] * 2.0f32), (__e20[1] * 2.0f32), (__e20[2] * 2.0f32)];
            __l0 = __e22;
            let __e23 = __l1;
            let __e25 = (__e23 * 0.5f32);
            __l1 = __e25;
        }
    }
    let __e29 = __l2;
    let __e30 = __e1[1];
    let __e32 = (__e30 * 3.0f32);
    let __e33 = (__e32).sin();
    let __e34 = __e1[0];
    let __e36 = (__e34 * 3.0f32);
    let __e37 = (__e36).cos();
    let __e38 = (__e33 * __e37);
    let __e40 = (__e38 * 90.0f32);
    let __e41 = (__e29 + __e40);
    return __e41;
}

/// Host evaluation of the WGSL function `sample_direction`, generated by mulciber-shader.
#[allow(unused, unreachable_code, clippy::all, clippy::pedantic)]
pub fn sample_direction(index: u32) -> [f32; 3] {
    let __e1 = ((index) as f32);
    let __e3 = (__e1 + 0.5f32);
    let __e5 = (2.0f32 * __e3);
    let __e7 = (__e5 / 256.0f32);
    let __e9 = (1.0f32 - __e7);
    let __e10 = (__e9 * __e9);
    let __e12 = (1.0f32 - __e10);
    let __e14 = (0.0f32).max(__e12);
    let __e15 = (__e14).sqrt();
    let __e17 = (__e3 * 0.381966f32);
    let __e18 = (__e17 - (__e17).floor());
    let __e20 = (__e18 * 6.2831855f32);
    let __e21 = (__e20).cos();
    let __e22 = (__e21 * __e15);
    let __e23 = (__e20).sin();
    let __e24 = (__e23 * __e15);
    let __e25 = [__e22, __e9, __e24];
    return __e25;
}

fn __mulciber_dot3(left: [f32; 3], right: [f32; 3]) -> f32 {
    left[0] * right[0] + left[1] * right[1] + left[2] * right[2]
}

fn __mulciber_length3(value: [f32; 3]) -> f32 {
    __mulciber_dot3(value, value).sqrt()
}

fn __mulciber_normalize3(value: [f32; 3]) -> [f32; 3] {
    let scale = 1.0f32 / __mulciber_length3(value);
    [value[0] * scale, value[1] * scale, value[2] * scale]
}

